### ISSUE TITLE
Support jsx

### ISSUE THREAD

**Issue by JulianKingman** [facebooknuclide/nuclide-format-js#7]
### Issue and Steps to Reproduce
Currently this formats JSX weirdly
![screen shot 2017-02-07 at 8 16 20 pm](https://cloud.githubusercontent.com/assets/1566400/22719202/510f3662-ed72-11e6-8aa6-ffc639199d34.png)

### Expected Behavior
It should format JSX like HTML tags, properly indented

### Actual Behavior
It removes line breaks and pulls everything together.

**Comment by xixixao** [comment]
@kyldvs Let's close. @JulianKingman use [prettier](https://github.com/prettier/prettier)
