### ISSUE TITLE
Using Image() triggers auto-require of 'Image'

### ISSUE THREAD

**Issue by dunnbobcat** [facebooknuclide/nuclide-format-js#8]
### Issue and Steps to Reproduce
Using the `Image` constructor causes `require('Image')` to be auto-inserted by the formatter.

`let img = new Image(); // no need for require -- provided by the DOM`

### Expected Behavior
No require should be added, since `Image()` is a valid global in the browser: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

### Actual Behavior
`require('Image')` gets inserted, which may erroneously resolve to something like react native's implementation.

**Comment by kyldvs** [comment]
In the settings there should be a list of built ins you can add "Image" to so that it will not be auto-required in your projects

**Comment by dunnbobcat** [comment]
Sweet, thanks for the quick response @kyldvs!
